### ISSUE TITLE
Program doesn't run

### ISSUE THREAD

**Issue by susilehtola** [hande-qmc/fcidump#2]
I'm now able to compile the newest version of the code by executing the CMake command given by 
```
psi4 --plugin-compile
```
and running make.

But, when I try to run a job using the module,
```
import fcidump
```
gives me the following error
```
$ psi4
Traceback (most recent call last):
  File "/home/work/psi4/install/bin/psi4", line 223, in <module>
    exec(content)
  File "<string>", line 31, in <module>

ImportError: dynamic module does not define module export function (PyInit_fcidump)
```

**Comment by fdmalone** [comment]
mmm, I'm having my own issues with psi4 at the moment. What version of psi4 are you using, and are you using python 2 or 3?

**Comment by fdmalone** [comment]
Do you have sys.path.insert(0, './..') at the top of your input file? I can reproduce your error if I remove it.

I think this is related to the following comment in input.dat in the mollerplesset2 plugin directory which comes with psi4:

```
# PYTHONPATH must include directory above plugin directory.
#     Define either externally or here, then import plugin.

```
I made the mistake of including the full path to fcidump in ~/.psi4rc, rather than stopping one directory short (I fortunately also had sys.path.insert(0, './..') included in my input file). If this fixes your issue I'll update the docs accordingly.

**Comment by susilehtola** [comment]
I'm using the latest trunk and python 3.

But yes, you're exactly right: if I define PYTHONPATH as the directory above the plugin directory, it runs! Thanks a lot.
