### ISSUE TITLE
import 'procedures' failing on psi4 1.1 release

### ISSUE THREAD

**Issue by xrq-phys** [hande-qmc/fcidump#5]
The compilation process returns no error, but when I try to run import `fcidump` in `psi4`, it rises the error `module 'procedures' not found`. Then I discovered in the 1.1 formal release, `procedures` was renamed into `procrouting`. Hence this problem can be fixed by replacing `from psi4.driver.procedures import proc_util` with `from psi4.driver.procrouting import proc_util`.

Please fix this problem for the formal 1.1 release of `psi4`.

**Comment by YingzhouLi** [comment]
We found the same issue. The above update works for the psi4conda 1.1 as well.

**Comment by fdmalone** [comment]
Sorry for the delay. Could you post an example of what you're doing just so I can try to reproduce it? If I compile psi4 on the 1.1.x branch of the public repository on github (sha1: c25e788) then the test provided with fcidump completes successfully with no errors. Thanks.

**Comment by YingzhouLi** [comment]
You could compare the following two lines of code.

https://github.com/hande-qmc/fcidump/blob/master/pymodule.py#L27

https://github.com/psi4/psi4/blob/da39266fcb0b84203cdd9a3935e6e98600a688a4/psi4/share/psi4/plugin/aointegrals/pymodule.py.template#L33

I believe both @rubidium-hydride and I encountered the same issue and solved it with the same trick, i.e., using ``from psi4.driver.procrouting import proc_util'' instead of ``from psi4.driver.procedures import proc_util``.

I tested fcidump with PSI4 1.1 release version (https://github.com/psi4/psi4/releases/tag/v1.1).

**Comment by fdmalone** [comment]
Got it. For whatever reason the clean build I did of v1.1 didn't really do a clean build I guess. I can now reproduce the issue. Thanks for pointing this out to us and for your patience. I'll push a fix shortly.

**Comment by fdmalone** [comment]
This should be fixed now.
